@login = http://localhost:3000/user/login
@singup = http://localhost:3000/user/usersp
@materias = http://localhost:3000/user/obtenerProductos




POST {{login}}
Content-Type: application/json

{
   "dni" : "2021",
   "password": "1234"
}

###
POST {{singup}}
Content-Type: application/json

{
   "dni" : "2022",
   "nombre" : "prueba 1",
   "password" : "1234"
}

###
GET {{materias}}
auth : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkbmkiOiIyMDIxIiwibm9tYnJlIjoicHJ1ZWJhIDEiLCJpYXQiOjE3MTcxNjI2OTUsImV4cCI6MTcxNzE2Mjc1NX0.5DELWX5amOdDufkUxZ0LGhD96s58bwF9VOtNrlIR7SU